AllCops:
  TargetRubyVersion: 2.4.2
  Exclude:
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - db/seeds.rb
    - Gemfile
    - config/**/*
    - bin/*
    - Rakefile
    - config.ru
    - app/models/application_record.rb
    - app/controllers/application_controller.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true
