# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c070bd51b51e1b6414a500c270cc25cf19d81f805bb61ee9154ca013113620db3b7425b22a7928cfa130c096ca99a8d4b2ec4723902cc4fe1500c3863cbbd05

test:
  secret_key_base: 3625a387809667c5371964c79383b4e261d90a42900115961b2d7f12108e1bfd611e44209ec9a585a7608ea5d7c5b34faf42c299e195dbac6b88e2ea48c18ed8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
